plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vinisgabriel.flappybird'
    compileSdk 34

    defaultConfig {
        applicationId 'com.vinisgabriel.flappybird'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // ============================================
    // IGNORA ARQUIVOS desktop.ini
    // ============================================
    aaptOptions {
        ignoreAssetsPattern "!desktop.ini:!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    // ============================================
    // IGNORA desktop.ini TAMBÉM NAS PASTAS res
    // ============================================
    packagingOptions {
        resources {
            excludes += ['**/desktop.ini']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // ============================================
    // NOVO: RENOMEIA O APK PARA "Flappy Bird.apk"
    // ============================================
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "Flappy Bird.apk"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}